from django.urls import path, re_path
from .views import *

urlpatterns = [
    path("", index),
    path("home/", index),
    path("health-and-wellness-category/", index),
    path("gallery-formate/", index),
    path("full-width-with-sidebar/", index),
    path("full-width-with-no-sidebar/", index),
    path("faq/", index),
    path("editor-profile/", index),
    path("contact-us/", index),
    path("classic-with-sidebar/", index),
    path("audio-formate/", index),
    path("ai-category/", index),
    path("about-us/", index),
    path("video-formate/", index),
    path("vertical-with-sidebar/", index),
    path("vertical-with-no-sidebar/", index),
    path("travel-category/", index),
    path("terms-condition/", index),
    path("standard-formate/", index),
    path("privacy-policy/", index),
    path("post-pagination/", index),
    path("podcast-category/", index),
    path("pet-category/", index),
    path("only-for-subscriber/", index),
    path("minimal/", index),
    path("life-style/", index),
]
