# Generated by Django 5.1.5 on 2025-02-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='articles/default.jpg', null=True, upload_to='articles/%Y/%m/%d/', verbose_name='Image'),
        ),
    ]
